### ISSUE TITLE
More Prior Art!: Turbosql

### ISSUE THREAD

**Issue by trevyn** [leafac/sqlite-migration#1]
@leafac This is very cool! I thought you might like to know that I also arrived at a similar conclusion regarding lightweight forward-only migrations in Turbosql, an opinionated Rust wrapper for SQLite: https://github.com/trevyn/turbosql#automatic-schema-migrations

I've been using it in my own projects, and the setup has been working even better than expected, including complex hand-written migrations. Example: https://github.com/trevyn/turbo/blob/main/migrations.toml

**Comment by leafac** [comment]
🙌 Added Turbosql to [§ Prior Art](https://github.com/leafac/sqlite-migration#prior-art).

I like the idea of [dumping the final schema](https://github.com/trevyn/turbosql/blob/2e46e42a78f929cb2492a87e7124ba49d01178ca/turbosql-impl/src/lib.rs#L281). I think I’ll steal it… 😃

**Comment by leafac** [comment]
🙌 Added Turbosql to [§ Prior Art](https://github.com/leafac/sqlite-migration#prior-art).

I like the idea of [dumping the final schema](https://github.com/trevyn/turbosql/blob/2e46e42a78f929cb2492a87e7124ba49d01178ca/turbosql-impl/src/lib.rs#L281). I think I’ll steal it…
